### ISSUE TITLE
Cagney not going into second phase

### ISSUE THREAD

**Issue by Dashaque** [Grub4K/CupCore-dist#2]
**Describe the bug**
Instead of going into his second phase, Cagney continues to shoot seeds into the air, but they don't fall down.  This continues for the entire fight, it's all he does.  

**Expected behavior**
He is suppose to go into the other attack pattern.

**Comment by xp4xbox** [comment]
This is due to lvlproperties, probably a specific pattern that causes him to freeze.

**Comment by xp4xbox** [comment]
Fixed the bug, will be updated in next release.
