### ISSUE TITLE
I have an error when starting the patcher error: Could not locate xdelta3

### ISSUE THREAD

**Issue by bubblegum0k1oser** [Grub4K/CupCore-dist#7]
I need your help, the mod does not work for me, this message always appears after I click on the patcher: /
I hope and you can answer me ... 

I have an error when starting the patcher error: Could not locate xdelta3

![Screenshot_1](https://user-images.githubusercontent.com/50683278/57816968-eda3e980-7742-11e9-90e5-bc3c55de03ba.png)

**Comment by xp4xbox** [comment]
You are using the old version 0.1.0. It was fixed with 0.1.1 https://github.com/Grub4K/CupCore-dist/releases/download/v0.1.1-alpha/release-0.1.1-alpha.zip
