### ISSUE TITLE
Patcher Error "Could not locate "data\sharedassets17.assets.xdelta""

### ISSUE THREAD

**Issue by SayMyRain** [Grub4K/CupCore-dist#8]
**Describe the bug**
When running the Patcher, I run into the error Could not locate "data\sharedassets17.assets.xdelta"

**Expected behavior**
I've previously installed Cupcore on a different computer and had no issues. Now I have this error message.

**Screenshots**
Nothing but that error message

**Additional context**
N/A

**Comment by xp4xbox** [comment]
i dont know why it would just be that one asset. Try re-downloading.

**Comment by SayMyRain** [comment]
@xp4xbox Yeah I did try re-downloading, no luck :/ It's just weird because I installed this in August with no issues, idk what the problem is now

**Comment by xp4xbox** [comment]
What is the current directory that you have the patcher downloaded to. the full path, eg c:\users\user\Desktop\release-v0.2

**Comment by SayMyRain** [comment]
The full path is C:\Users\User\Desktop\CupCore-dist-master\distribution

Also the directory for cuphead is C:\Program Files (x86)\Steam\steamapps\common\Cuphead

**Comment by xp4xbox** [comment]
Are you just downloading the actual repository instead of the release?

**Comment by SayMyRain** [comment]
I could be? I installed Cupcore on a different computer and had no issues. And I thought I was following the same instructions / wasn't doing anything differently...

What do I need to select to download the release instead of the actual repo? Thanks for the help

**Comment by xp4xbox** [comment]
Click on the releases tab and download the latest one.

**Comment by xp4xbox** [comment]
https://github.com/Grub4K/CupCore-dist/releases/download/v0.2.1-alpha/release-v0.2.1-alpha.zip

**Comment by SayMyRain** [comment]
Thanks for the help, that was my issue. Appreciate it

**Comment by xp4xbox** [comment]
Can't blame you, happened to me the first time I used Github.
