### ISSUE TITLE
Error messages when applying Patcher to Cuphead data

### ISSUE THREAD

**Issue by Schwib1199** [Grub4K/CupCore-dist#9]
Patcher can't seem to locate Assembly-CSharp.dll within Cuphead install files, asking for Cuphead reinstallation doesn't solve issue.

![image](https://user-images.githubusercontent.com/87498012/125845041-6853e5f1-6c5d-4620-8f3a-03860891c723.png)

**Comment by xp4xbox** [comment]
Can i see a screenshot of your cuphead install directory? C:\program files x86\steam\steamapps\common\cuphead\cuphead_data\managed

**Comment by Schwib1199** [comment]
Hey,

Really sorry but i’ve managed to solve the issue.

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by xp4xbox** [comment]
How did you fix it

**Comment by ducky325** [comment]
i think he didnt downgraded the version
